"""
PRAKALP-DRISHTI: TEMPORAL MILESTONE AUDIT (KAAL-DARPAN)

Binds statutory Monthly Progress Reports to dated satellite observations, and reports
whether the ground showed activity during each claimed period.

WHAT THIS DOES NOT DO, AND WHY
------------------------------
It does not compute a satellite-derived completion percentage, and it therefore does not
compute `claimed - detected` as a discrepancy score.

Surface change and reported progress are uncorrelated across this corpus -- the
measured figure lives in artifacts/eo_progress_independence.json and is recomputed by
analytics_engine/eo_independence.py, never quoted from memory. That is
statistically indistinguishable from noise: imagery explains essentially none of the
variance in reported progress. A "satellite says 38.4% complete" figure would be a guess
wearing the costume of a measurement, and a fraud badge computed from it would accuse
named government contractors on the strength of noise.

That figure existed here once. It was removed because it was 45%-weighted on the very
claim it purported to audit -- it looked plausible precisely because it was circular.
This module does not reintroduce it.

WHAT IT DOES INSTEAD
--------------------
It answers a question imagery CAN answer: **did anything happen?**

Magnitude is unavailable (r ~ 0, see the artifact). Presence is not. A greenfield highway that claims
+45 points of progress across a year, on a site whose two dated images are
indistinguishable, is a real finding -- not "we measured 38.4%", but "45 points were
claimed, this project type should show that, and the ground does not". That is a triage
signal for a human inspector, not a verdict.

Hence the verdicts below are about EVIDENCE, never about guilt:

    GROUND_ACTIVITY_OBSERVED     the ground changed during the claimed period
    NO_ACTIVITY_DETECTED         material progress claimed, change expected, none seen
    SENSOR_CANNOT_RESOLVE        tunnel / interior / underground -- optical cannot see it
    NO_IMAGERY_FOR_INTERVAL      the site was not reflown in this window
    NOT_MATERIAL                 the claimed delta is too small to expect a signal

NO_ACTIVITY_DETECTED is the only one that asks for action, and it says "inspect", not
"fraud".

IMAGERY CADENCE IS THE BINDING CONSTRAINT
-----------------------------------------
MPRs are monthly. A given site is reflown roughly annually and irregularly, so across a
12-year span a project may have four to six genuinely distinct images. Milestones are
therefore bound to the imagery INTERVALS that exist, rather than an image being
conjured for each milestone date. Most monthly milestones legitimately land in
NO_IMAGERY_FOR_INTERVAL, and that is the honest answer rather than a gap.
"""

from __future__ import annotations

from dataclasses import dataclass, field
from datetime import date, datetime
from typing import Any, Dict, List, Optional, Tuple

# ── VERDICTS ────────────────────────────────────────────────────────────────
GROUND_ACTIVITY_OBSERVED = "GROUND_ACTIVITY_OBSERVED"
NO_ACTIVITY_DETECTED = "NO_ACTIVITY_DETECTED"
SENSOR_CANNOT_RESOLVE = "SENSOR_CANNOT_RESOLVE"
NO_IMAGERY_FOR_INTERVAL = "NO_IMAGERY_FOR_INTERVAL"
NOT_MATERIAL = "NOT_MATERIAL"
BASELINE = "BASELINE"

VERDICTS = (GROUND_ACTIVITY_OBSERVED, NO_ACTIVITY_DETECTED, SENSOR_CANNOT_RESOLVE,
            NO_IMAGERY_FOR_INTERVAL, NOT_MATERIAL, BASELINE)

# Only this one asks anybody to do anything.
ACTIONABLE = (NO_ACTIVITY_DETECTED,)

# ── MILESTONE VOCABULARY ────────────────────────────────────────────────────
MILESTONE_TYPES = (
    "SANCTION", "TENDER_AWARD", "SITE_MOBILISATION", "SUBGRADE_COMPLETE",
    "PIERS_CAST", "SUPERSTRUCTURE", "MONTHLY_PROGRESS", "FINAL_COMMISSIONING",
)

# ── WHERE OPTICAL CHANGE IS EXPECTED ────────────────────────────────────────
# A 2 m optical sensor sees the ground surface. Whether progress SHOULD appear there
# depends on what is being built. Firing NO_ACTIVITY_DETECTED on a metro tunnel would
# be a false accusation generated by the sensor's own blind spot, so the red verdict is
# scoped to sectors where surface change is genuinely expected.
SURFACE_VISIBLE_SECTORS = {
    "Roads & Highways",
    "Railways",
    "Water Resources",
    "Transmission & Distribution",
    "Coal",
    "Metals & Mining",
    "Steel",
    "Electricity Generation",
    "Energy Storage",
    "Waste & Water",
    "Aviation & Aviation Infrastructure",
    "Shipping",
    "Inland Waterways",
    "Logistics Infrastructure",
    "Real Estate",
    "Construction",
}

# Sectors whose works are substantially invisible to a nadir optical sensor: buried
# cable, underground alignment, or interior fit-out inside an existing shell.
SURFACE_INVISIBLE_SECTORS = {
    "Telecommunication",
    "Urban Public Transport",     # metro: often bored tunnel + underground stations
    "Healthcare",                 # fit-out inside a completed shell
    "Education",
    "Oil & Gas",                  # buried trunk pipeline
    "Tourism, Hospitality & Wellness",
}

# Project-name signals that override the sector default. A Roads project that is a
# tunnel is still a tunnel.
INVISIBLE_NAME_TOKENS = (
    "tunnel", "underground", "sub-way", "subway", "bored", "shaft",
    "pipeline", "cable", "interior", "fit-out", "fitout", "renovation",
    "refurbish", "modernisation", "modernization",
)

# ── THRESHOLDS ──────────────────────────────────────────────────────────────
# Below this claimed delta, no optical signal should be expected at all, so silence is
# uninformative rather than suspicious.

def _eo_statement() -> str:
    try:
        from analytics_engine.eo_independence import statement
        return statement()
    except Exception:  # pragma: no cover
        return "surface change and reported progress are treated as independent"


def _eo_summary():
    try:
        from analytics_engine.eo_independence import load
        a = load() or {}
        return {"overall": a.get("overall"), "n_reliable": a.get("n_reliable"),
                "catalog_sha256": (a.get("catalog_sha256") or "")[:16],
                "artifact": "artifacts/eo_progress_independence.json"}
    except Exception:  # pragma: no cover
        return None

MATERIAL_PROGRESS_DELTA_PCT = 15.0

# Surface change at or below this is treated as "no detectable activity". It is not a
# completion figure -- it is the noise floor of the change detector, above which
# something structurally altered in the sampled frame.
ACTIVITY_FLOOR_PCT = 2.0


def _parse_date(value: Any) -> Optional[date]:
    if value is None:
        return None
    s = str(value).strip()
    if s in ("NaT", "nan", "None", ""):
        return None
    if type(value) is date:
        return value
    if isinstance(value, datetime):
        try:
            d = value.date()
            if str(d) != "NaT":
                return d
        except Exception:
            pass
    s10 = s[:10]
    for fmt in ("%Y-%m-%d", "%d/%m/%Y", "%d-%m-%Y"):
        try:
            return datetime.strptime(s10, fmt).date()
        except ValueError:
            continue
    return None


def surface_change_expected(sector: Optional[str],
                            project_name: Optional[str] = None) -> Tuple[bool, str]:
    """
    (expected, reason). Whether a nadir optical sensor should see this project's works.

    The name check runs FIRST and can only ever make the answer more conservative: a
    tunnel inside the Roads sector must not inherit "surface change expected", because
    the red verdict would then fire on a project the sensor was never able to observe.
    """
    name = (project_name or "").lower()
    for token in INVISIBLE_NAME_TOKENS:
        if token in name:
            return False, f"project name indicates '{token}' works, not visible from nadir optical"

    s = (sector or "").strip()
    if s in SURFACE_INVISIBLE_SECTORS:
        return False, f"sector '{s}' builds substantially below ground or inside a shell"
    if s in SURFACE_VISIBLE_SECTORS:
        return True, f"sector '{s}' builds at the surface"
    return False, f"sector '{s or 'unknown'}' has no declared surface-visibility rule"


@dataclass
class Milestone:
    """One statutory progress report, as submitted by the executing authority."""
    milestone_id: str
    project_id: str
    update_date: Optional[date]
    claimed_progress_pct: Optional[float]
    milestone_type: str = "MONTHLY_PROGRESS"
    cumulative_expenditure_cr: Optional[float] = None
    recorded_by: Optional[str] = None

    def as_dict(self) -> Dict[str, Any]:
        return {
            "milestone_id": self.milestone_id,
            "project_id": self.project_id,
            "update_date": self.update_date.isoformat() if self.update_date else None,
            "claimed_progress_pct": self.claimed_progress_pct,
            "milestone_type": self.milestone_type,
            "cumulative_expenditure_cr": self.cumulative_expenditure_cr,
            "recorded_by": self.recorded_by,
        }


@dataclass
class ImageryEpoch:
    """One dated observation of the site that actually exists on disk."""
    epoch_id: str
    captured: Optional[date]
    vintage_label: str
    tile_path: Optional[str] = None
    wayback_release: Optional[int] = None
    # Surface change measured against the PREVIOUS epoch. None on the baseline, and
    # None whenever the pair could not be measured.
    surface_change_pct: Optional[float] = None

    def as_dict(self) -> Dict[str, Any]:
        return {
            "epoch_id": self.epoch_id,
            "captured": self.captured.isoformat() if self.captured else None,
            "vintage_label": self.vintage_label,
            "tile_path": self.tile_path,
            "wayback_release": self.wayback_release,
            "surface_change_pct": self.surface_change_pct,
        }


@dataclass
class TimelineEntry:
    milestone: Milestone
    verdict: str
    reason: str
    claimed_delta_pct: Optional[float] = None
    observed_change_pct: Optional[float] = None
    epoch_from: Optional[str] = None
    epoch_to: Optional[str] = None
    interval_days: Optional[int] = None

    @property
    def actionable(self) -> bool:
        return self.verdict in ACTIONABLE

    def as_dict(self) -> Dict[str, Any]:
        return {
            **self.milestone.as_dict(),
            "verdict": self.verdict,
            "reason": self.reason,
            "actionable": self.actionable,
            "claimed_delta_pct": self.claimed_delta_pct,
            # Named 'observed_change_pct', never 'detected_progress_pct'. It is the
            # fraction of sampled ground that structurally changed, not a completion
            # estimate, and the field name has to keep saying so.
            "observed_change_pct": self.observed_change_pct,
            "epoch_from": self.epoch_from,
            "epoch_to": self.epoch_to,
            "interval_days": self.interval_days,
        }


def _bracketing_epochs(epochs: List[ImageryEpoch],
                       start: Optional[date],
                       end: Optional[date]) -> Tuple[Optional[ImageryEpoch],
                                                     Optional[ImageryEpoch]]:
    """
    The last epoch at or before `start`, and the first at or after `end`.

    Milestones are bound to the imagery that EXISTS rather than an image being fetched
    per milestone date: a site is reflown roughly annually, so most monthly reports fall
    inside a single interval and share its observation.
    """
    if start is None or end is None:
        return None, None
    dated = sorted([e for e in epochs if e.captured], key=lambda e: e.captured)
    before = None
    after = None
    for e in dated:
        if e.captured <= start:
            before = e
    for e in dated:
        if e.captured >= end:
            after = e
            break
    if before is not None and after is not None and before.epoch_id == after.epoch_id:
        return None, None                    # the same image cannot bracket an interval
    return before, after


def _interval_change(epochs: List[ImageryEpoch],
                     frm: ImageryEpoch, to: ImageryEpoch) -> Optional[float]:
    """
    Total measured change across every epoch step inside (frm, to].

    Summed rather than taken from the endpoint alone, because each epoch records its
    change against its own predecessor. Returns None if any step in the span is
    unmeasured -- a partial sum would understate the interval and could manufacture a
    NO_ACTIVITY_DETECTED verdict out of missing data.
    """
    dated = sorted([e for e in epochs if e.captured], key=lambda e: e.captured)
    span = [e for e in dated if frm.captured < e.captured <= to.captured]
    if not span:
        return None
    total = 0.0
    for e in span:
        if e.surface_change_pct is None:
            return None
        total += float(e.surface_change_pct)
    return round(total, 3)


def build_timeline(milestones: List[Milestone],
                   epochs: List[ImageryEpoch],
                   sector: Optional[str] = None,
                   project_name: Optional[str] = None) -> Dict[str, Any]:
    """
    Bind each milestone to the imagery interval covering it and issue an evidence verdict.

    Every verdict states what was observed and what could not be. None of them assert a
    completion figure, and none of them assert wrongdoing.
    """
    expected, expect_reason = surface_change_expected(sector, project_name)

    ordered = sorted(
        [m for m in milestones if m.update_date],
        key=lambda m: m.update_date,
    )

    entries: List[TimelineEntry] = []
    prev_claim: Optional[float] = None
    prev_date: Optional[date] = None

    for i, m in enumerate(ordered):
        claim = m.claimed_progress_pct
        delta = None
        if claim is not None and prev_claim is not None:
            delta = round(float(claim) - float(prev_claim), 2)

        if i == 0:
            entries.append(TimelineEntry(
                milestone=m, verdict=BASELINE,
                reason="First reported milestone; there is no earlier claim to compare against.",
                claimed_delta_pct=None))
            prev_claim, prev_date = claim, m.update_date
            continue

        frm, to = _bracketing_epochs(epochs, prev_date, m.update_date)
        interval_days = (m.update_date - prev_date).days if prev_date else None

        if not expected:
            verdict, reason, observed = SENSOR_CANNOT_RESOLVE, expect_reason, None
        elif delta is not None and abs(delta) < MATERIAL_PROGRESS_DELTA_PCT:
            verdict = NOT_MATERIAL
            reason = (f"Claimed change of {delta:+.1f} points is below the "
                      f"{MATERIAL_PROGRESS_DELTA_PCT:.0f}-point threshold at which a "
                      "surface signal would be expected.")
            observed = None
        elif frm is None or to is None:
            verdict = NO_IMAGERY_FOR_INTERVAL
            reason = ("The site was not re-imaged between these two reports, so no "
                      "observation exists for this period. Sites are reflown roughly "
                      "annually; monthly reports commonly fall inside one interval.")
            observed = None
        else:
            observed = _interval_change(epochs, frm, to)
            if observed is None:
                verdict = NO_IMAGERY_FOR_INTERVAL
                reason = ("Imagery brackets this period but the change between epochs "
                          "was not measurable, so no observation is claimed.")
            elif observed > ACTIVITY_FLOOR_PCT:
                verdict = GROUND_ACTIVITY_OBSERVED
                reason = (f"{observed:.2f}% of the sampled ground structurally changed "
                          f"between {frm.vintage_label} and {to.vintage_label}. This is "
                          "an observation of activity, not a completion estimate.")
            else:
                verdict = NO_ACTIVITY_DETECTED
                reason = (f"{delta:+.1f} points of progress were reported, and this "
                          "project type builds at the surface, but only "
                          f"{observed:.2f}% of sampled ground changed between "
                          f"{frm.vintage_label} and {to.vintage_label}. Recommend "
                          "physical inspection. This is a triage signal, not a finding "
                          "of wrongdoing.")

        entries.append(TimelineEntry(
            milestone=m, verdict=verdict, reason=reason,
            claimed_delta_pct=delta, observed_change_pct=observed,
            epoch_from=frm.epoch_id if frm else None,
            epoch_to=to.epoch_id if to else None,
            interval_days=interval_days))

        prev_claim, prev_date = claim, m.update_date

    counts: Dict[str, int] = {}
    for e in entries:
        counts[e.verdict] = counts.get(e.verdict, 0) + 1

    return {
        "milestones": [e.as_dict() for e in entries],
        "epochs": [e.as_dict() for e in sorted(
            epochs, key=lambda e: (e.captured is None, e.captured))],
        "surface_change_expected": expected,
        "surface_expectation_reason": expect_reason,
        "verdict_counts": counts,
        "actionable_count": sum(1 for e in entries if e.actionable),
        "methodology": (
            "Verdicts report EVIDENCE, not completion. In this corpus "
            + _eo_statement() +
            ", so no satellite-derived completion percentage is computed and no "
            "claimed-minus-detected discrepancy score exists. NO_ACTIVITY_DETECTED "
            "recommends inspection; it is not a finding of wrongdoing."
        ),
        "eo_progress_independence": _eo_summary(),
        "thresholds": {
            "material_progress_delta_pct": MATERIAL_PROGRESS_DELTA_PCT,
            "activity_floor_pct": ACTIVITY_FLOOR_PCT,
        },
    }
