/** @type {import('tailwindcss').Config} */
export default {
  content: [
    "./index.html",
    "./src/**/*.{js,ts,jsx,tsx}",
    "./amey/**/*.{js,ts,jsx,tsx}",
    "./tanmay/**/*.{js,ts,jsx,tsx}",
    "./parth/**/*.{js,ts,jsx,tsx}",
    "./janhavi/**/*.{js,ts,jsx,tsx}",
    "./soham/**/*.{js,ts,jsx,tsx}",
    "./aditya/**/*.{js,ts,jsx,tsx}",
  ],
  theme: {
    extend: {
      colors: {
        'gov-saffron': '#E65100',
        'gov-saffron-vibrant': '#EA580C',
        'gov-saffron-light': '#FFF7ED',
        'gov-saffron-dark': '#9A3412',
        'gov-gold-parchment': '#FEF9EE',
        'gov-gold-border': '#FDE68A',
        'gov-green-map': '#15803D',
        'gov-green-light': '#DCFCE7',
        'gov-navy': '#0F2942',
        'gov-navy-dark': '#0A1E31',
        'gov-navy-light': '#1E3A8A',
        'gov-slate-footer': '#0F172A',
        'gov-blue': '#2474A8',
        'gov-blue-light': '#EDF4FA',
        'page-bg': '#FAFAF9',
        'surface': '#FFFFFF',
        'text-primary': '#1E293B',
        'text-secondary': '#475569',
        'text-muted': '#64748B',
        'border-default': '#E2E8F0',
        'border-strong': '#CBD5E1',
        'gov-success': '#15803D',
        'gov-warning': '#B45309',
        'gov-danger': '#B91C1C',
      },
      fontFamily: {
        sans: ['"Inter"', '"Noto Sans"', '-apple-system', 'BlinkMacSystemFont', 'sans-serif'],
        heading: ['"Plus Jakarta Sans"', '"Inter"', 'sans-serif'],
        cinzel: ['"Cinzel"', 'serif'],
        devanagari: ['"Noto Sans Devanagari"', '"Inter"', 'sans-serif'],
      },
      maxWidth: {
        content: '1240px',
      },
      borderRadius: {
        sm: '4px',
        DEFAULT: '6px',
        md: '8px',
        lg: '12px',
        xl: '16px',
        '2xl': '20px',
      },
      boxShadow: {
        subtle: '0 1px 2px rgba(15,23,42,0.04)',
        card: '0 2px 8px rgba(15,23,42,0.05)',
        elevated: '0 8px 24px rgba(15,23,42,0.08)',
        menu: '0 12px 32px rgba(15,23,42,0.12)',
        'parchment-glow': '0 4px 20px rgba(234,88,12,0.08)',
      },
      spacing: {
        'section': '80px',
        'section-sm': '48px',
      },
    },
  },
  plugins: [require("tailwindcss-animate")],
}
