-- ============================================================================
-- PRAKALP-DRISHTI — 0004: CONTROLLED VOCABULARY SEED
-- ============================================================================
-- GENERATED from the bootstrap corpus, not hand-written. Regenerate with:
--     python tools/gen_vocabulary_seed.py
--
-- Values pass through corpus_provenance._canonical_value first, so the strings stored
-- here are byte-identical to the ones the corpus hash sees. That matters for at least
-- one real row: the corpus contains the sector 'Construction ' WITH A TRAILING SPACE.
-- Seeding the raw string would create a vocabulary entry that the canonicalised project
-- row can never match, and the FK would reject the whole sector on ingest.
--
-- Idempotent: safe to re-run.
-- ============================================================================

insert into sectors (sector_name) values
    ('Aviation & Aviation Infrastructure'),
    ('Coal'),
    ('Construction'),
    ('Education'),
    ('Electricity Generation'),
    ('Energy Storage'),
    ('Healthcare'),
    ('Inland Waterways'),
    ('Logistics Infrastructure'),
    ('Metals & Mining'),
    ('Oil & Gas'),
    ('Railways'),
    ('Real Estate'),
    ('Roads & Highways'),
    ('Shipping'),
    ('Steel'),
    ('Telecommunication'),
    ('Tourism, Hospitality & Wellness'),
    ('Transmission & Distribution'),
    ('Urban Public Transport'),
    ('Waste & Water'),
    ('Water Resources')
on conflict (sector_name) do nothing;

insert into canonical_entities (canonical_id, canonical_name, entity_type) values
    ('AAI', 'Airports Authority of India', 'Central PSU'),
    ('ADANI_TRANSMISSION_LIMITED', 'Adani Transmission Limited', 'Executing Entity'),
    ('BANARAS_HINDU_UNIVERSITY', 'Banaras Hindu University', 'Executing Entity'),
    ('BENGALURU_METRO_RAIL', 'Bengaluru Metro Rail', 'Executing Entity'),
    ('BHARAT_COKING_COAL_LIMITED_BCC', 'Bharat Coking Coal Limited [BCCL]', 'Executing Entity'),
    ('CAO_C_NCR', 'CAO/C/NCR', 'Executing Entity'),
    ('CENTRALRAILWAY', 'CentralRailway', 'Executing Entity'),
    ('CENTRAL_RAILWAYS', 'Central Railways', 'Executing Entity'),
    ('CENTRAL_TRIBAL_UNIVERSITY_OF_A', 'Central Tribal University of Andhra Pradesh', 'Executing Entity'),
    ('CENTRAL_UNIVERSITY_HIMACHAL_PR', 'Central University, Himachal Pradesh', 'Executing Entity'),
    ('CENTRAL_UNIVERSITY_OF_GUJARAT', 'Central University of Gujarat', 'Executing Entity'),
    ('CENTRAL_UNIVERSITY_OF_PUNJAB', 'Central University of Punjab', 'Executing Entity'),
    ('CERL', 'CERL', 'Executing Entity'),
    ('CHENNAI_METRO_RAIL_LIMITED_CMR', 'Chennai Metro Rail Limited [CMRL]', 'Executing Entity'),
    ('COAL_INDIA', 'Coal India Limited & Subsidiaries', 'Maharatna PSU'),
    ('CPM_ICF', 'CPM/ICF', 'Executing Entity'),
    ('CSPCC_PROJECTS', 'CSPCC Projects', 'Executing Entity'),
    ('DAMODAR_VALLEY_CORPORATION', 'Damodar Valley Corporation', 'Executing Entity'),
    ('DEENDAYAL_PORT_TRUST', 'Deendayal Port Trust', 'Executing Entity'),
    ('DEENDAYAL_PORT_TRUST_DPT', 'Deendayal Port Trust [DPT]', 'Executing Entity'),
    ('DELHI_METRO_RAIL_CORPORATION_L', 'Delhi Metro Rail Corporation Limited [DMRC]', 'Executing Entity'),
    ('DELHI_UNIVERSITY', 'Delhi University', 'Executing Entity'),
    ('DEPARTMENT_OF_SPORTS_YOUTH_AFF', 'Department of Sports & Youth Affairs', 'Executing Entity'),
    ('DEPARTMENT_OF_TELECOMMUNICATIO', 'Department of Telecommunications', 'Executing Entity'),
    ('EDTK_MC_RB', 'EDTK[MC]/RB', 'Executing Entity'),
    ('EMPLOYEE_S_STATE_INSURANCE_COM', 'Employee''s State Insurance Company [ESIC]', 'Executing Entity'),
    ('GUJARAT_METRO_RAIL_CORPORATION', 'Gujarat Metro Rail Corporation Limited [GMRCL]', 'Executing Entity'),
    ('GURUGRAM_METRO_RAIL_LIMITED_GM', 'Gurugram Metro Rail Limited (GMRL)', 'Executing Entity'),
    ('HALDIA_DOCK_COMPLEX_SYAMA_PRAS', 'Haldia Dock Complex, Syama Prasad Mookerjee Port Authority', 'Executing Entity'),
    ('HINDUSTAN_COPPER_LIMITED_HCL', 'Hindustan Copper Limited [HCL]', 'Executing Entity'),
    ('IISC_BANGALORE', 'IISC Bangalore', 'Executing Entity'),
    ('INDIAN_INSTITUTES_OF_SCIENCE_E', 'Indian Institutes of Science Education and Research, Behrampur', 'Executing Entity'),
    ('INDIAN_INSTITUTE_OF_MANAGEMENT', 'Indian Institute of Management, Jammu', 'Executing Entity'),
    ('INDIAN_INSTITUTE_OF_TECHNOLOGY', 'Indian Institute of Technology, Bombay', 'Executing Entity'),
    ('INDIAN_INTITUE_OF_MANAGEMENT_A', 'Indian intitue of Management, Amritsar', 'Executing Entity'),
    ('INDIAN_PORT_RAIL_ROPEWAY_CORPO', 'Indian Port Rail & Ropeway Corporation Ltd. [IPRCL]', 'Executing Entity'),
    ('INDIAN_RAILWAYS', 'Ministry of Railways / Executing PSUs', 'Central Ministry & PSUs'),
    ('INDIA_INTERNATIONAL_CONVENTION', 'India International Convention & Expo Centre', 'Executing Entity'),
    ('INVALID_CO', 'INVALID CO.', 'Executing Entity'),
    ('IRRIGATION_AND_CAD_TG', 'Irrigation and CAD-TG', 'Executing Entity'),
    ('IRRIGATION_UK', 'Irrigation-UK', 'Executing Entity'),
    ('JAIPUR_METRO_RAIL_CORPORATION', 'Jaipur Metro Rail Corporation', 'Executing Entity'),
    ('JAL_SHAKTI', 'Ministry of Jal Shakti', 'Central Ministry'),
    ('KARNATAKA_RAIL_INFRASTRUCTURE_', 'Karnataka Rail Infrastructure Development Company Limited [K-RIDE]', 'Executing Entity'),
    ('MADHYA_PRADESH_METRO_RAIL_CO_L', 'Madhya Pradesh Metro Rail Co Limited [MPMRCL]', 'Executing Entity'),
    ('MAHARASHTRA_METRO_RAIL_CORPORA', 'Maharashtra Metro Rail Corporation Limited [MMRCL]', 'Executing Entity'),
    ('MANGALORE_REFINARY_AND_PETROCH', 'Mangalore Refinary and Petrochemicals Limited', 'Executing Entity'),
    ('MINISTRYOFPETROLEUMNATURALGAS', 'MinistryofPetroleumNaturalGas', 'Executing Entity'),
    ('MINISTRY_OF_COAL', 'Ministry of Coal', 'Executing Entity'),
    ('MINISTRY_OF_EDUCATION', 'Ministry of Education', 'Executing Entity'),
    ('MINISTRY_OF_MINES', 'Ministry of Mines', 'Executing Entity'),
    ('MINISTRY_OF_RAILWAYS', 'Ministry of Railways', 'Executing Entity'),
    ('MIS_MOCOAL_INTEGRATION_LOGINS', 'MIS MoCoal Integration Logins', 'Executing Entity'),
    ('MOHFW', 'Ministry of Health and Family Welfare', 'Central Ministry'),
    ('MOHUA', 'Ministry of Housing and Urban Affairs', 'Central Ministry & PSUs'),
    ('MRIDC', 'MRIDC', 'Executing Entity'),
    ('MUMBAI_METRO_RAIL_CORPORATION_', 'Mumbai Metro Rail Corporation Limited [MMRC]', 'Executing Entity'),
    ('MUMBAI_PORT_TRUST_MPT', 'Mumbai Port Trust [MPT]', 'Executing Entity'),
    ('MUMBAI_RAIL_VIKAS_CORPORATION_', 'Mumbai Rail Vikas Corporation Ltd.[MRVC]', 'Executing Entity'),
    ('M_S_SRC_COMPANY_INFRA_PRIVATE_', 'M/S SRC company Infra Private Limited', 'Executing Entity'),
    ('MoRTH', 'Ministry of Road Transport and Highways', 'Central Ministry'),
    ('NATIONAL_ALUMINIUM_COMPANY_LIM', 'National Aluminium Company Limited [NALCO]', 'Executing Entity'),
    ('NATIONAL_CAPITAL_REGION_TRANSP', 'National Capital Region Transport Corporation [NCRTC]', 'Executing Entity'),
    ('NATIONAL_COMMUNICATION_ACADEMY', 'National Communication Academy - Finance (Erstwhile NICF)', 'Executing Entity'),
    ('NATIONAL_HIGH_SPEED_RAIL_CORPO', 'National High Speed Rail Corporation [NHSRC]', 'Executing Entity'),
    ('NATIONAL_HYDROELECTRIC_POWER_C', 'National Hydroelectric Power Corporation Limited [NHPC]', 'Executing Entity'),
    ('NATIONAL_INDUSTRIAL_CORRIDOR_D', 'National Industrial Corridor Development Corporation', 'Executing Entity'),
    ('NATIONAL_INSTITUTE_OF_TECHNOLO', 'National Institute of Technology Uttarakhand', 'Executing Entity'),
    ('NATIONAL_MINERAL_DEVELOPMENT_C', 'National Mineral Development Corporation Limited [NMDC]', 'Executing Entity'),
    ('NATIONAL_MISSION_FOR_CLEAN_GAN', 'National Mission for Clean Ganga', 'Executing Entity'),
    ('NEW_MANGALORE_PORT_AUTHORITY', 'New Mangalore Port Authority', 'Executing Entity'),
    ('NHAI', 'National Highways Authority of India', 'Central PSU'),
    ('NHIDCL', 'National Highways & Infrastructure Development Corp', 'Central PSU'),
    ('NICDC', 'NICDC', 'Executing Entity'),
    ('NIT_NAGALAND', 'NIT Nagaland', 'Executing Entity'),
    ('NIT_PATNA', 'NIT Patna', 'Executing Entity'),
    ('NIT_ROURKELA', 'NIT Rourkela', 'Executing Entity'),
    ('NLC_INDIA_LIMITED', 'NLC India Limited', 'Executing Entity'),
    ('NLC_INDIA_LIMITED_NLCIL', 'NLC India Limited [NLCIL]', 'Executing Entity'),
    ('NMCG1', 'NMCG1', 'Executing Entity'),
    ('NOIDA_METRO_RAIL_CORPORATION_L', 'Noida Metro Rail Corporation Ltd. [NMRCL]', 'Executing Entity'),
    ('NORTHERN_RAILWAYS', 'Northern Railways', 'Executing Entity'),
    ('NORTH_EASTERN_ELECTRIC_POWER_C', 'North Eastern Electric Power Corporation Limited', 'Executing Entity'),
    ('NRL', 'NRL', 'Executing Entity'),
    ('NTPC', 'NTPC Limited', 'Maharatna PSU'),
    ('PARADIP_PORT_TRUST_PPT', 'Paradip Port Trust [PPT]', 'Executing Entity'),
    ('PATNA_METRO_RAIL_CORPORATION_L', 'Patna Metro Rail Corporation Ltd. [PMRCL]', 'Executing Entity'),
    ('PCE_NCR', 'PCE/NCR', 'Executing Entity'),
    ('PETROLEUM_GAS', 'Ministry of Petroleum & Natural Gas / OMCs', 'Central Ministry & PSUs'),
    ('PMSSY_AND_INSTITUTE_OF_NATIONA', 'PMSSY AND Institute of NATIONAL Importance', 'Executing Entity'),
    ('PORTS_SHIPPING', 'Ministry of Ports, Shipping and Waterways', 'Central Ministry & PSUs'),
    ('POWERGRID', 'Power Grid Corporation of India Limited', 'Maharatna PSU'),
    ('RAIL_LAND_DEVELOPMENT_AUTHORIT', 'Rail Land Development Authority', 'Executing Entity'),
    ('RAIL_VIKAS_NIGAM_LIMITED', 'Rail Vikas Nigam Limited', 'Executing Entity'),
    ('RCIL', 'RCIL', 'Executing Entity'),
    ('RELIANCE_INDUSTRIES_LTD', 'Reliance Industries Ltd', 'Executing Entity'),
    ('SATLUJ_JAL_VIDYUT_NIGAM_SJVN_T', 'Satluj Jal Vidyut Nigam [SJVN] Thermal Limited', 'Executing Entity'),
    ('SIKKIM_UNIVERSITY', 'Sikkim University', 'Executing Entity'),
    ('SINGARENI_COLLIERIES_COMPANY_L', 'Singareni Collieries Company Limited [SCCL]', 'Executing Entity'),
    ('STEEL_MINISTRY', 'Ministry of Steel / Steel Authority of India', 'Maharatna PSU'),
    ('STERLITE_POWER', 'Sterlite Power', 'Executing Entity'),
    ('SYAMA_PRASAD_MOOKERJEE_PORT_KO', 'Syama Prasad Mookerjee Port Kolkata', 'Executing Entity'),
    ('TELECOM_DOT', 'Department of Telecommunications / BSNL', 'Central PSU'),
    ('TEZPUR_UNIVERSITY', 'Tezpur University', 'Executing Entity'),
    ('THDC_INDIA_LIMITED', 'THDC India Limited', 'Executing Entity'),
    ('UTTAR_PRADESH_METRO_RAIL_CORPO', 'Uttar Pradesh metro rail corporation [UPMRC]', 'Executing Entity'),
    ('WATER_RESOURCE_MP', 'Water resource-mp', 'Executing Entity'),
    ('WPO_PATNA', 'WPO/Patna', 'Executing Entity')
on conflict (canonical_id) do nothing;

insert into entity_aliases (raw_name, canonical_id) values
    ('Adani Airport Holdings Limited', 'AAI'),
    ('Adani Transmission Limited', 'ADANI_TRANSMISSION_LIMITED'),
    ('Airport Authority of India [AAI]', 'AAI'),
    ('BSNL', 'TELECOM_DOT'),
    ('Banaras Hindu University', 'BANARAS_HINDU_UNIVERSITY'),
    ('Bengaluru Metro Rail', 'BENGALURU_METRO_RAIL'),
    ('Bharat Coking Coal Limited (BCCL)', 'BHARAT_COKING_COAL_LIMITED_BCC'),
    ('Bharat Coking Coal Limited [BCCL]', 'BHARAT_COKING_COAL_LIMITED_BCC'),
    ('Bharat Petroleum Corporation Limited [BPCL]', 'PETROLEUM_GAS'),
    ('CAO/C/ECoR', 'INDIAN_RAILWAYS'),
    ('CAO/C/II/NR', 'INDIAN_RAILWAYS'),
    ('CAO/C/NCR', 'CAO_C_NCR'),
    ('CAO/C/NR', 'INDIAN_RAILWAYS'),
    ('CAO/C/SECR', 'INDIAN_RAILWAYS'),
    ('CAO/C/SER', 'INDIAN_RAILWAYS'),
    ('CAOC/SWR SWR mor', 'INDIAN_RAILWAYS'),
    ('CCL - CIL', 'COAL_INDIA'),
    ('CERL', 'CERL'),
    ('CPM/ICF', 'CPM_ICF'),
    ('CR', 'INDIAN_RAILWAYS'),
    ('CSPCC Projects', 'CSPCC_PROJECTS'),
    ('Central Organisation for Railway Electrification (CORE)', 'INDIAN_RAILWAYS'),
    ('Central Public Works Department (CPWD)', 'MOHUA'),
    ('Central Public Works Department - CPWD', 'MOHUA'),
    ('Central Public Works Department [CPWD]', 'MOHUA'),
    ('Central Railway', 'INDIAN_RAILWAYS'),
    ('Central Railway (CR) - II', 'INDIAN_RAILWAYS'),
    ('Central Railway [CR] - II', 'INDIAN_RAILWAYS'),
    ('Central Railways', 'CENTRAL_RAILWAYS'),
    ('Central Tribal University of Andhra Pradesh', 'CENTRAL_TRIBAL_UNIVERSITY_OF_A'),
    ('Central University of Gujarat', 'CENTRAL_UNIVERSITY_OF_GUJARAT'),
    ('Central University of Punjab', 'CENTRAL_UNIVERSITY_OF_PUNJAB'),
    ('Central University, Himachal Pradesh', 'CENTRAL_UNIVERSITY_HIMACHAL_PR'),
    ('CentralRailway', 'CENTRALRAILWAY'),
    ('Chennai Metro Rail Limited [CMRL]', 'CHENNAI_METRO_RAIL_LIMITED_CMR'),
    ('Chennai Petroleum Corporation Limited [CPCL]', 'PETROLEUM_GAS'),
    ('Cochin Shipyard', 'PORTS_SHIPPING'),
    ('Construction NER', 'INDIAN_RAILWAYS'),
    ('DFCCIL', 'INDIAN_RAILWAYS'),
    ('Damodar Valley Corporation', 'DAMODAR_VALLEY_CORPORATION'),
    ('Deendayal Port Trust', 'DEENDAYAL_PORT_TRUST'),
    ('Deendayal Port Trust [DPT]', 'DEENDAYAL_PORT_TRUST_DPT'),
    ('Delhi Metro Rail Corporation Limited [DMRC]', 'DELHI_METRO_RAIL_CORPORATION_L'),
    ('Delhi University', 'DELHI_UNIVERSITY'),
    ('Department of Sports & Youth Affairs', 'DEPARTMENT_OF_SPORTS_YOUTH_AFF'),
    ('Department of Telecommunications', 'DEPARTMENT_OF_TELECOMMUNICATIO'),
    ('Department of Telecommunications [DoT]', 'TELECOM_DOT'),
    ('Department of Water Resources, River Development & GR', 'JAL_SHAKTI'),
    ('Department of Water Resources, River Development, ', 'JAL_SHAKTI'),
    ('Department of Water Resources-JH', 'JAL_SHAKTI'),
    ('Department of Water Resources-MH', 'JAL_SHAKTI'),
    ('Department of Water Resources-PB', 'JAL_SHAKTI'),
    ('Department of water resources-MH - II', 'JAL_SHAKTI'),
    ('ECL - CIL', 'COAL_INDIA'),
    ('EDTK[MC]/RB', 'EDTK_MC_RB'),
    ('East Central Railway (ECR) - II', 'INDIAN_RAILWAYS'),
    ('East Central Railway [ECR] - I', 'INDIAN_RAILWAYS'),
    ('East Central Railway [ECR] - II', 'INDIAN_RAILWAYS'),
    ('East Coast Railway [ECoR] - II', 'INDIAN_RAILWAYS'),
    ('Eastern Coal Fields Limited [ECL]', 'COAL_INDIA'),
    ('Eastern Railway [ER] - I', 'INDIAN_RAILWAYS'),
    ('Eastern Railway [ER] - II ', 'INDIAN_RAILWAYS'),
    ('Employee''s State Insurance Company [ESIC]', 'EMPLOYEE_S_STATE_INSURANCE_COM'),
    ('GAIL Gas', 'PETROLEUM_GAS'),
    ('GM/C/ NFR', 'INDIAN_RAILWAYS'),
    ('Gas Authority of India Limited [GAIL]', 'PETROLEUM_GAS'),
    ('Gujarat Metro Rail Corporation Limited [GMRCL]', 'GUJARAT_METRO_RAIL_CORPORATION'),
    ('Gurugram Metro Rail Limited (GMRL)', 'GURUGRAM_METRO_RAIL_LIMITED_GM'),
    ('Haldia Dock Complex, Syama Prasad Mookerjee Port Authority', 'HALDIA_DOCK_COMPLEX_SYAMA_PRAS'),
    ('Hindustan Copper Limited [HCL]', 'HINDUSTAN_COPPER_LIMITED_HCL'),
    ('Hindustan Petroleum Corporation Limited', 'PETROLEUM_GAS'),
    ('Hindustan Petroleum Corporation Limited [HPCL]', 'PETROLEUM_GAS'),
    ('IISC Bangalore', 'IISC_BANGALORE'),
    ('INDIAN INSTITUTE OF TECHNOLOGY PALAKKAD', 'INDIAN_INSTITUTE_OF_TECHNOLOGY'),
    ('INVALID CO.', 'INVALID_CO'),
    ('IOCL', 'PETROLEUM_GAS'),
    ('India International Convention & Expo Centre', 'INDIA_INTERNATIONAL_CONVENTION'),
    ('Indian Institute of Management, Jammu', 'INDIAN_INSTITUTE_OF_MANAGEMENT'),
    ('Indian Institute of Management, Sirmaur', 'INDIAN_INSTITUTE_OF_MANAGEMENT'),
    ('Indian Institute of Technology, Bhilai', 'INDIAN_INSTITUTE_OF_TECHNOLOGY'),
    ('Indian Institute of Technology, Bhubaneshwar', 'INDIAN_INSTITUTE_OF_TECHNOLOGY'),
    ('Indian Institute of Technology, Bombay', 'INDIAN_INSTITUTE_OF_TECHNOLOGY'),
    ('Indian Institute of Technology, Hyderabad', 'INDIAN_INSTITUTE_OF_TECHNOLOGY'),
    ('Indian Institute of Technology, Indore', 'INDIAN_INSTITUTE_OF_TECHNOLOGY'),
    ('Indian Institute of Technology, Kharagpur', 'INDIAN_INSTITUTE_OF_TECHNOLOGY'),
    ('Indian Institute of Technology, Mandi', 'INDIAN_INSTITUTE_OF_TECHNOLOGY'),
    ('Indian Institutes of Science Education and Research, Behrampur', 'INDIAN_INSTITUTES_OF_SCIENCE_E'),
    ('Indian Oil Corporation Limited [IOCL]', 'PETROLEUM_GAS'),
    ('Indian Port Rail & Ropeway Corporation Ltd. [IPRCL]', 'INDIAN_PORT_RAIL_ROPEWAY_CORPO'),
    ('Indian Railway', 'INDIAN_RAILWAYS'),
    ('Indian Railway Construction International Limited [IRCON]', 'INDIAN_RAILWAYS'),
    ('Indian Railway and Govt of Odisha', 'INDIAN_RAILWAYS'),
    ('Indian Railways', 'INDIAN_RAILWAYS'),
    ('Indian intitue of Management, Amritsar', 'INDIAN_INTITUE_OF_MANAGEMENT_A'),
    ('Inland Waterways Authority of India [IWAI]', 'PORTS_SHIPPING'),
    ('Irrigation & Water Resources-UP', 'JAL_SHAKTI'),
    ('Irrigation and CAD-TG', 'IRRIGATION_AND_CAD_TG'),
    ('Irrigation-UK', 'IRRIGATION_UK'),
    ('Jaipur Metro Rail Corporation', 'JAIPUR_METRO_RAIL_CORPORATION'),
    ('Jawaharlal Nehru Port Authority [JNPA]', 'PORTS_SHIPPING'),
    ('Karnataka Rail Infrastructure Development Company Limited [K-RIDE]', 'KARNATAKA_RAIL_INFRASTRUCTURE_'),
    ('M/S SRC company Infra Private Limited', 'M_S_SRC_COMPANY_INFRA_PRIVATE_'),
    ('MCL - CIL', 'COAL_INDIA'),
    ('MIS MoCoal Integration Logins', 'MIS_MOCOAL_INTEGRATION_LOGINS'),
    ('MRIDC', 'MRIDC'),
    ('Madhya Pradesh Metro Rail Co Limited [MPMRCL]', 'MADHYA_PRADESH_METRO_RAIL_CO_L'),
    ('Mahanadi Coalfields Limited (MCL)', 'COAL_INDIA'),
    ('Mahanadi Coalfields Limited [MCL]', 'COAL_INDIA'),
    ('Maharashtra Metro Rail Corporation Limited [MMRCL]', 'MAHARASHTRA_METRO_RAIL_CORPORA'),
    ('Mangalore Refinary and Petrochemicals Limited', 'MANGALORE_REFINARY_AND_PETROCH'),
    ('Medical Education, Ministry of Health and Family Welfare', 'MOHFW'),
    ('Metro Railway, Kolkata', 'INDIAN_RAILWAYS'),
    ('Ministry of Coal', 'MINISTRY_OF_COAL'),
    ('Ministry of Education', 'MINISTRY_OF_EDUCATION'),
    ('Ministry of Health & Family Welfare', 'MOHFW'),
    ('Ministry of Housing & Urban Affairs', 'MOHUA'),
    ('Ministry of Mines', 'MINISTRY_OF_MINES'),
    ('Ministry of Petroleum & Natural Gas', 'PETROLEUM_GAS'),
    ('Ministry of Petroleum and Natural Gas', 'PETROLEUM_GAS'),
    ('Ministry of Railways', 'MINISTRY_OF_RAILWAYS'),
    ('Ministry of Railways-', 'MINISTRY_OF_RAILWAYS'),
    ('MinistryofPetroleumNaturalGas', 'MINISTRYOFPETROLEUMNATURALGAS'),
    ('MoRTH', 'MoRTH'),
    ('Mumbai Metro Rail Corporation Limited [MMRC]', 'MUMBAI_METRO_RAIL_CORPORATION_'),
    ('Mumbai Port Trust [MPT]', 'MUMBAI_PORT_TRUST_MPT'),
    ('Mumbai Rail Vikas Corporation Ltd.[MRVC]', 'MUMBAI_RAIL_VIKAS_CORPORATION_'),
    ('NCL - CIL', 'COAL_INDIA'),
    ('NER', 'INDIAN_RAILWAYS'),
    ('NHAI', 'NHAI'),
    ('NHIDCL', 'NHIDCL'),
    ('NICDC', 'NICDC'),
    ('NIT Nagaland', 'NIT_NAGALAND'),
    ('NIT Patna', 'NIT_PATNA'),
    ('NIT Rourkela', 'NIT_ROURKELA'),
    ('NLC India Limited', 'NLC_INDIA_LIMITED'),
    ('NLC India Limited [NLCIL]', 'NLC_INDIA_LIMITED_NLCIL'),
    ('NMCG1', 'NMCG1'),
    ('NRL', 'NRL'),
    ('Narmada and Water Resources, Water Supply and Kalpsar Department-GJ', 'JAL_SHAKTI'),
    ('National Aluminium Company Limited [NALCO]', 'NATIONAL_ALUMINIUM_COMPANY_LIM'),
    ('National Buildings Construction Corporation [NBCC]', 'MOHUA'),
    ('National Capital Region Transport Corporation [NCRTC]', 'NATIONAL_CAPITAL_REGION_TRANSP'),
    ('National Communication Academy - Finance (Erstwhile NICF)', 'NATIONAL_COMMUNICATION_ACADEMY'),
    ('National High Speed Rail Corporation [NHSRC]', 'NATIONAL_HIGH_SPEED_RAIL_CORPO'),
    ('National Highways & Infrastructure Development Corporation Ltd. [NHIDCL]', 'NHIDCL'),
    ('National Highways Authority of India [NHAI]', 'NHAI'),
    ('National Hydroelectric Power Corporation Limited [NHPC]', 'NATIONAL_HYDROELECTRIC_POWER_C'),
    ('National Industrial Corridor Development Corporation', 'NATIONAL_INDUSTRIAL_CORRIDOR_D'),
    ('National Institute of Technology Delhi', 'NATIONAL_INSTITUTE_OF_TECHNOLO'),
    ('National Institute of Technology Uttarakhand', 'NATIONAL_INSTITUTE_OF_TECHNOLO'),
    ('National Institute of Technology, Arunachal Pradesh', 'NATIONAL_INSTITUTE_OF_TECHNOLO'),
    ('National Institute of Technology, Meghalaya', 'NATIONAL_INSTITUTE_OF_TECHNOLO'),
    ('National Institute of Technology, Puducherry', 'NATIONAL_INSTITUTE_OF_TECHNOLO'),
    ('National Mineral Development Corporation Limited [NMDC]', 'NATIONAL_MINERAL_DEVELOPMENT_C'),
    ('National Mission for Clean Ganga', 'NATIONAL_MISSION_FOR_CLEAN_GAN'),
    ('National Thermal Power Corporation [NTPC]', 'NTPC'),
    ('New Mangalore Port Authority', 'NEW_MANGALORE_PORT_AUTHORITY'),
    ('Noida Metro Rail Corporation Ltd. [NMRCL]', 'NOIDA_METRO_RAIL_CORPORATION_L'),
    ('North Central Railway', 'INDIAN_RAILWAYS'),
    ('North Central Railway (NCR) - II', 'INDIAN_RAILWAYS'),
    ('North Eastern Electric Power Corporation Limited', 'NORTH_EASTERN_ELECTRIC_POWER_C'),
    ('North Eastern Railway (NER) - II', 'INDIAN_RAILWAYS'),
    ('North Eastern Railway [NER]', 'INDIAN_RAILWAYS'),
    ('North Western Railway [NWR]', 'INDIAN_RAILWAYS'),
    ('Northeast Frontier Railway (NFR) - II', 'INDIAN_RAILWAYS'),
    ('Northeast Frontier Railway [NFR]', 'INDIAN_RAILWAYS'),
    ('Northen Railway [NR]', 'INDIAN_RAILWAYS'),
    ('Northern Railways', 'NORTHERN_RAILWAYS'),
    ('Oil and Natural Gas Corporation Limited [ONGC]', 'PETROLEUM_GAS'),
    ('PCE/NCR', 'PCE_NCR'),
    ('PCE/WR', 'INDIAN_RAILWAYS'),
    ('PMAY, Ministry of Housing and Urban Affairs', 'MOHUA'),
    ('PMSSY AND Institute of NATIONAL Importance', 'PMSSY_AND_INSTITUTE_OF_NATIONA'),
    ('Paradip Port Trust [PPT]', 'PARADIP_PORT_TRUST_PPT'),
    ('Patna Metro Rail Corporation Ltd. [PMRCL]', 'PATNA_METRO_RAIL_CORPORATION_L'),
    ('Power Grid Corporation of India Limited [POWERGRID]', 'POWERGRID'),
    ('RCIL', 'RCIL'),
    ('RVNL', 'INDIAN_RAILWAYS'),
    ('RVNL - I', 'INDIAN_RAILWAYS'),
    ('RVNL - II', 'INDIAN_RAILWAYS'),
    ('Rail Land Development Authority', 'RAIL_LAND_DEVELOPMENT_AUTHORIT'),
    ('Rail Vikas Nigam Limited', 'RAIL_VIKAS_NIGAM_LIMITED'),
    ('Railway', 'INDIAN_RAILWAYS'),
    ('Reliance Industries Ltd', 'RELIANCE_INDUSTRIES_LTD'),
    ('SECL - CIL', 'COAL_INDIA'),
    ('SECR', 'INDIAN_RAILWAYS'),
    ('SR-ERS', 'INDIAN_RAILWAYS'),
    ('Satluj Jal Vidyut Nigam [SJVN] Thermal Limited', 'SATLUJ_JAL_VIDYUT_NIGAM_SJVN_T'),
    ('Sikkim University', 'SIKKIM_UNIVERSITY'),
    ('Singareni Collieries Company Limited [SCCL]', 'SINGARENI_COLLIERIES_COMPANY_L'),
    ('South Central Railway [SCR] - I', 'INDIAN_RAILWAYS'),
    ('South Central Railway [SCR] - II', 'INDIAN_RAILWAYS'),
    ('South East Central Railway', 'INDIAN_RAILWAYS'),
    ('South East Central Railway [SECR] - II', 'INDIAN_RAILWAYS'),
    ('South Eastern Central Railway', 'INDIAN_RAILWAYS'),
    ('South Eastern Coalfields Limited [SECL]', 'COAL_INDIA'),
    ('South Eastern Railway - JH', 'INDIAN_RAILWAYS'),
    ('South Eastern Railway [SER] - I', 'INDIAN_RAILWAYS'),
    ('South Western Railway [SWR] - II', 'INDIAN_RAILWAYS'),
    ('Southern Railway [SR] - I', 'INDIAN_RAILWAYS'),
    ('Southern Railway [SR] - II', 'INDIAN_RAILWAYS'),
    ('Steel Authority of India Limited [SAIL]', 'STEEL_MINISTRY'),
    ('Sterlite Power', 'STERLITE_POWER'),
    ('Syama Prasad Mookerjee Port Kolkata', 'SYAMA_PRASAD_MOOKERJEE_PORT_KO'),
    ('THDC India Limited', 'THDC_INDIA_LIMITED'),
    ('Tezpur University', 'TEZPUR_UNIVERSITY'),
    ('Uttar Pradesh metro rail corporation [UPMRC]', 'UTTAR_PRADESH_METRO_RAIL_CORPO'),
    ('WCL - CIL', 'COAL_INDIA'),
    ('WPO/Patna', 'WPO_PATNA'),
    ('Water Resources Department-MN', 'JAL_SHAKTI'),
    ('Water Resources-AP', 'JAL_SHAKTI'),
    ('Water Resources-BR', 'JAL_SHAKTI'),
    ('Water Resources-CT', 'JAL_SHAKTI'),
    ('Water Resources-KA', 'JAL_SHAKTI'),
    ('Water Resources-MP', 'JAL_SHAKTI'),
    ('Water Resources-OR', 'JAL_SHAKTI'),
    ('Water resource-mp', 'WATER_RESOURCE_MP'),
    ('West Central Railway WCR I', 'INDIAN_RAILWAYS'),
    ('West Central Railway [WCR] - II', 'INDIAN_RAILWAYS'),
    ('Western Coalfields Limited [WCL]', 'COAL_INDIA'),
    ('Western Railway', 'INDIAN_RAILWAYS'),
    ('Western Railway (WR) - II', 'INDIAN_RAILWAYS'),
    ('Western Railway WR - II', 'INDIAN_RAILWAYS'),
    ('Western Railway [WR] - II', 'INDIAN_RAILWAYS'),
    ('ministry of housing and urban affairs', 'MOHUA')
on conflict (raw_name) do nothing;
